# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoIn1hr < Formula
  desc ""
  homepage "https://github.com/VikasPoddar/go-in-1hr"
  version "0.0.2-rc-3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-3/go-in-1hr_Darwin_x86_64.tar.gz"
      sha256 "17a3d901c6688d08e630dec859cf177baa11d8140f1c3cdf915794e5ccfca3f2"

      def install
        bin.install "go-in-1hr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-3/go-in-1hr_Darwin_arm64.tar.gz"
      sha256 "5c219633d76e88164727c1da2a7c7375d3e99e24a9513df6a95fc770d901749e"

      def install
        bin.install "go-in-1hr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-3/go-in-1hr_Linux_x86_64.tar.gz"
        sha256 "e55ba96b70471c8fd79292192d0f0038b1673433d304c956ab60ade097b108ba"

        def install
          bin.install "go-in-1hr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/VikasPoddar/go-in-1hr/releases/download/v0.0.2-rc-3/go-in-1hr_Linux_arm64.tar.gz"
        sha256 "bd40d1ac8811cfcc7b6421a76f3ec6082d80f9fbfa5f690b82839f7036c3a77a"

        def install
          bin.install "go-in-1hr"
        end
      end
    end
  end
end
